---
- hosts: localhost
  connection: local
  tasks:
    - name: terminate ec2 instance
      amazon.aws.ec2_instance:
        state: absent
        instance_ids: "{{item}}" 
       
      loop:
        - "{{ lookup('amazon.aws.aws_ec2', 'name=by-ansible1')}}"
        - "{{ lookup('amazon.aws.aws_ec2', 'name=by-ansible2')}}"
        - "{{ lookup('amazon.aws.aws_ec2', 'name=by-ansible3')}}"

    - name: remove inventory.ini
      ansible.builtin.file:
        path: inventory.ini
        state: absent
      ignore_errors: true
